name: Node release

on:
  push:
    branches:
      - master

jobs:
  allow-release:
    runs-on: ubuntu-latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Evaluate pusher
        id: set_output
        run: |
          if [[ ${{ github.event.pusher.name }} == "dependabot-preview[bot]" ]]; then
            echo "::set-output name=run_jobs::false"
          elif [[ ${{ github.event.pusher.name }} == "dependabot[bot]" ]]; then
            echo "::set-output name=run_jobs::false"
          elif [[ ${{ github.event.pusher.name }} == "renovate[bot]" ]]; then
            echo "::set-output name=run_jobs::false"
          elif [[ ${{ github.event.pusher.name }} == "Renovate Bot" ]]; then
            echo "::set-output name=run_jobs::false"
          else
            echo "::set-output name=run_jobs::true"
          fi

  build:
    needs: [allow-release]
    if: needs.allow-release.outputs.run_rest_jobs == 'true'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm cache files
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm ci

      - name: Tag Version
        run: |
          npm run release
          git push --follow-tags
          export LAST_TAG=$(git describe --abbrev=0)
          echo "::set-env name=EXPORT_TAG_NAME::${LAST_TAG}"
          echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")

      - name: Build
        run: |
          npm run build

      - name: Publish npm Package
        run: |
          npm publish
